from datetime import datetime, timezone

from config.settings import settings
from infrastructure.database.base import Base
from sqlalchemy import DateTime, String
from sqlalchemy.orm import Mapped, mapped_column


class ChatHistory(Base):
    # Minimal chat history table for the first end-to-end example.
    __tablename__ = "chat_history"

    # Primary key generated by the database.
    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    # The actual text sent by the client after validation and trimming.
    message: Mapped[str] = mapped_column(
        String(settings.message_max_length),
        nullable=False,
    )
    # Timestamp automatically filled when the row is created.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        # Store timestamps in UTC so records stay comparable across environments.
        default=lambda: datetime.now(timezone.utc),
    )
